Corrected the issues preventing the package from being built on graviton
AnacondaRecipes/libspatialite-feedstock pull request #2
Opened 2021-06-07 22:17 UTC by varlackc

Made some modifications to the recipe in order to build the package on graviton.

2021-06-07 22:23 UTC, chenghlee commented on recipe/build.sh
> +export LDFLAGS="-L${PREFIX}/lib ${LDFLAGS}-Wl,--allow-multiple-definition"
1. There needs to be a space between `${LDFLAGS}` and `-Wl,--allow-multiple-definition`.
2. More importantly, using `-Wl,--allow-multiple-definition` seems like a _really_ bad idea; it allows the definition of one symbol (function) to squash another. Is there some reference that says it should be used for this build?

2021-06-07 22:25 UTC, chenghlee commented on recipe/meta.yaml
> +    # - {{ compiler('cxx') }}
The presence of this dependency strongly suggests that someone expects C++ bindings, but the build script somehow did not generate them; stripping this out may potentially change the behavior of downstream packages. I would look into the output of `./configure --help`, the upstream docs, etc. to figure out if C++ bindings are even an option, and if so, why this recipe is not configuring and/or building it.

2021-06-07 22:26 UTC, chenghlee requested changes

2021-06-07 22:26 UTC, chenghlee commented on recipe/build.sh
> +export LDFLAGS="-L${PREFIX}/lib ${LDFLAGS}-Wl,--allow-multiple-definition"
There needs to be a space between ${LDFLAGS} and -Wl,--allow-multiple-definition.
More importantly, using -Wl,--allow-multiple-definition seems like a really bad idea; it allows the definition of one symbol (function) to squash another. Is there some reference that says it should be used for this build?

2021-06-07 22:26 UTC, chenghlee commented on recipe/meta.yaml
> +    # - {{ compiler('cxx') }}
The presence of this dependency strongly suggests that someone expects C++ bindings, but the build script somehow did not generate them; stripping this out may potentially change the behavior of downstream packages. I would look into the output of `./configure --help`, the upstream docs, etc. to figure out if C++ bindings are even an option, and if so, why this recipe is not configuring and/or building it.

2021-06-07 23:52 UTC, chenghlee commented on recipe/meta.yaml
> +    # - {{ compiler('cxx') }}
Also: if you're going to remove a dependency from a recipe, you need to re-build & test it on the other supported platforms to make sure you haven't unexpectedly broken something.

2021-06-08 08:44 UTC, katietz commented on recipe/build.sh
> +export LDFLAGS="-L${PREFIX}/lib ${LDFLAGS}-Wl,--allow-multiple-definition"
well, it depends if that option is good, or not.  In general I agree, but there are projects which are redefining symbols in various object files and assume that they get a weak linkage ... in such cases this option can be pretty useful

2021-06-08 14:24 UTC, chenghlee commented on recipe/build.sh
> +export LDFLAGS="-L${PREFIX}/lib ${LDFLAGS}-Wl,--allow-multiple-definition"
I'm unable replicate the multiple definition error when building in a freshly-started and configured container, nor does it seem to be happening on x86_64 with GCC 7.x, 8.x, or 9.x. The only thing I see in the [GCC 10 changelog](https://gcc.gnu.org/gcc-10/changes.html#c) that might trigger this issue is switching default behavior from `-fcommon` to `-fno-common`, but I'm not convinced that that is the root cause of the reported problem.

@varlackc: can you take this LDFLAGS line out of the build.sh, then trying building this package in a freshly-started container?

2021-06-08 15:07 UTC, chenghlee commented on recipe/meta.yaml
> +    # - {{ compiler('cxx') }}
The over-depending error is happening on x86_64 as well, so I think removing the C++ compiler is fine.

2021-06-08 15:17 UTC, varlackc commented on recipe/build.sh
> +export LDFLAGS="-L${PREFIX}/lib ${LDFLAGS}-Wl,--allow-multiple-definition"
@chenghlee : the recommended changes were made. After testing we see that the package build properly for graviton.

2021-07-01 16:51 UTC, varlackc commented
The issue was due to a miss-configuration on the local environment. 
The PR is no longer needed.

2021-07-01 16:51 UTC, closed without merging